"""
threat_actor_intelligence.reports.html_report — dossier → self-contained HTML.

Renders the Markdown dossier body into a single, dependency-free HTML document
with inline CSS (dark/light aware), so a report can be opened in any browser or
attached to a ticket. The Markdown renderer is the source of truth for content;
this module converts its output to HTML (headings, lists, tables, code spans)
with a light-weight converter — no third-party markdown dependency.
"""

from __future__ import annotations

import html
import re
from typing import Any, Dict

from . import markdown_report

_CSS = """
:root { --bg:#ffffff; --fg:#1a1a1a; --muted:#666; --accent:#b0273d;
        --border:#e0e0e0; --code:#f4f4f4; }
@media (prefers-color-scheme: dark) {
  :root { --bg:#15181c; --fg:#e6e6e6; --muted:#9aa0a6; --accent:#ff6b81;
          --border:#2a2f36; --code:#1e2228; } }
* { box-sizing: border-box; }
body { background:var(--bg); color:var(--fg); font-family:-apple-system,
       BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;
       line-height:1.55; max-width:960px; margin:0 auto; padding:24px 16px; }
h1 { color:var(--accent); border-bottom:2px solid var(--accent); padding-bottom:6px; }
h2 { margin-top:1.8em; border-bottom:1px solid var(--border); padding-bottom:4px; }
code { background:var(--code); padding:1px 5px; border-radius:4px;
       font-family:'SF Mono',Menlo,Consolas,monospace; font-size:0.9em; }
table { border-collapse:collapse; width:100%; margin:12px 0; font-size:0.9em; }
th,td { border:1px solid var(--border); padding:6px 9px; text-align:left; }
th { background:var(--code); }
em { color:var(--muted); }
a { color:var(--accent); }
.badge { display:inline-block; padding:2px 8px; border-radius:10px;
         background:var(--accent); color:#fff; font-size:0.8em; }
"""


def _md_inline(text: str) -> str:
    text = html.escape(text)
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<em>\1</em>", text)
    text = re.sub(r"\[([^\]]+)\]\(([^)]*)\)", r'<a href="\2">\1</a>', text)
    return text


def _md_to_html(md: str) -> str:
    out = []
    in_list = False
    in_table = False
    for line in md.split("\n"):
        if re.match(r"^\|.*\|$", line):
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if re.match(r"^\|[\s:|-]+\|?$", line):
                continue
            if not in_table:
                out.append("<table>")
                in_table = True
                out.append("<tr>" + "".join(f"<th>{_md_inline(c)}</th>"
                                            for c in cells) + "</tr>")
            else:
                out.append("<tr>" + "".join(f"<td>{_md_inline(c)}</td>"
                                            for c in cells) + "</tr>")
            continue
        elif in_table:
            out.append("</table>")
            in_table = False

        m = re.match(r"^(#{1,4})\s+(.*)$", line)
        if m:
            if in_list:
                out.append("</ul>")
                in_list = False
            lvl = len(m.group(1))
            out.append(f"<h{lvl}>{_md_inline(m.group(2))}</h{lvl}>")
            continue
        if line.startswith("- "):
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(f"<li>{_md_inline(line[2:])}</li>")
            continue
        if in_list:
            out.append("</ul>")
            in_list = False
        if line.strip():
            out.append(f"<p>{_md_inline(line)}</p>")
    if in_list:
        out.append("</ul>")
    if in_table:
        out.append("</table>")
    return "\n".join(out)


def render(dossier: Dict[str, Any]) -> str:
    md = markdown_report.render(dossier)
    body = _md_to_html(md)
    title = dossier.get("identity", {}).get("canonical_name") \
        or dossier.get("identity", {}).get("campaign_name") \
        or dossier.get("identity", {}).get("name") or "CTI Dossier"
    return (f"<!doctype html>\n<html lang=\"en\"><head>"
            f"<meta charset=\"utf-8\">"
            f"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
            f"<title>{html.escape(title)} — CTI Dossier</title>"
            f"<style>{_CSS}</style></head><body>\n{body}\n"
            f"<hr><p><em>Generated by Sombra Guardian — Threat Actor Intelligence "
            f"Engine. Public-source CTI; see Limitations.</em></p>"
            f"</body></html>")


__all__ = ["render"]
